#!/usr/bin/env bash
# Generate bots/bosun/.env from a pacto-dev-env local deployment artifact.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${REPO_ROOT}/bots/bosun"
OUT_FILE="${OUT_DIR}/.env"

PACTO_DEV_ENV_DIR="${PACTO_DEV_ENV_DIR:-../pacto-dev-env}"
ARTIFACT_DIR="${PACTO_DEV_ENV_DIR}/data/deployments/31337"
ARTIFACT="${ARTIFACT_DIR}/full-system.json"

if ! command -v jq > /dev/null 2>&1; then
    echo "error: jq is required but not installed" >&2
    exit 1
fi

if [[ ! -f "${ARTIFACT}" ]]; then
    echo "error: deployment artifact not found: ${ARTIFACT}" >&2
    echo "Set PACTO_DEV_ENV_DIR to the pacto-dev-env checkout path, or run 'make seed' there." >&2
    exit 1
fi

if [[ ! -d "${OUT_DIR}" ]]; then
    echo "error: output directory does not exist: ${OUT_DIR}" >&2
    exit 1
fi

if [[ -n "${PRESERVE_ENV:-}" && "${PRESERVE_ENV}" != "0" && -f "${OUT_FILE}" ]]; then
    echo "info: PRESERVE_ENV is set; keeping existing ${OUT_FILE}"
    echo "${OUT_FILE}"
    exit 0
fi

extract() {
    jq -r "$1" "${ARTIFACT}"
}

cat > "${OUT_FILE}" <<EOF
# Generated by scripts/generate-env.sh from ${ARTIFACT}
# Local anvil deployment; not committed.

PACTO_GOVERNANCE_RPC_URL=http://localhost:8545
PACTO_GOVERNANCE_BOT_ID=bosun
PACTO_GOVERNANCE_GROUP_ID=
PACTO_GOVERNANCE_DAEMON_SOCKET=/var/lib/pacto-bot-api/pacto-bot-api.sock
PACTO_GOVERNANCE_REGISTRY=$(extract '.navePirataRegistry')
PACTO_GOVERNANCE_HATS=$(extract '.hats')

# Optional overrides
# PACTO_GOVERNANCE_SQUAD_INDEX=0
# PACTO_GOVERNANCE_CAPTAIN=0x0000000000000000000000000000000000000000
# PACTO_GOVERNANCE_CREW_CANDIDATES=
# PACTO_GOVERNANCE_PROPOSER_CANDIDATES=
EOF

echo "${OUT_FILE}"
